### ISSUE TITLE
[疑惑]：看到群消息就来体验了，但是apk的下载链接404了

### ISSUE THREAD

**Issue by zzzsssbo** [getActivity/NestedScrollLayout#2]
### 问题描述【必填】

看到群消息就来体验了，但是apk的下载链接404了

### 框架文档是否提及了该问题【必答】

未选择

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

### issue 列表中是否有人曾提过类似的问题【必答】

未选择

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

未选择

**Comment by getActivity** [comment]
多谢小伙子的提醒，问题已经修正。
