### ISSUE TITLE
[疑惑]：这个工具库具体是做什么的

### ISSUE THREAD

**Issue by jiasijiedajidali** [getActivity/NestedScrollLayout#3]
### 问题描述【必填】

我现在有个布局是顶部有个固定的view下面是一个webview，希望可以整体滑动，但是webview中的事件不受影响，例如上拉加载这些，都是h5自己实现。我以为这个类库可以实现，但是发现不行

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
小伙子，我不知道你的问题是什么，劳烦提供一个可供复现的 Demo 过来。

**Comment by jiasijiedajidali** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.hjq.nested.scroll.layout.NestedScrollLinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="200dp"
                android:background="#009988" />

            <com.hjq.nested.scroll.layout.NestedScrollWebView
                android:id="@+id/webvew"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

        </com.hjq.nested.scroll.layout.NestedScrollLinearLayout>
    </android.support.v4.widget.NestedScrollView>
</LinearLayout>


<img width="319" alt="image" src="https://github.com/getActivity/NestedScrollLayout/assets/37926774/85bf0cd9-7936-449f-9e96-8ca8a3338058">

滑动webview  顶部的TextView 无法一起向上滑动

**Comment by jiasijiedajidali** [comment]
> 小伙子，我不知道你的问题是什么，劳烦提供一个可供复现的 Demo 过来。
<android.support.v4.widget.NestedScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.hjq.nested.scroll.layout.NestedScrollLinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="200dp"
            android:background="#009988" />

        <com.hjq.nested.scroll.layout.NestedScrollWebView
            android:id="@+id/webvew"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </com.hjq.nested.scroll.layout.NestedScrollLinearLayout>
</android.support.v4.widget.NestedScrollView>

<img width="319" alt="image" src="https://github.com/getActivity/NestedScrollLayout/assets/37926774/848a8365-0428-4490-82f0-69d1ffd5d5c6">

**Comment by jiasijiedajidali** [comment]
> 小伙子，我不知道你的问题是什么，劳烦提供一个可供复现的 Demo 过来。

https://github.com/donkingliang/ConsecutiveScroller  想知道您提供的是否和这个实现的功能一样  ，因为他的这个不怎么好用 想换一个，看到你的这个库，但是发现好像功能不一样

**Comment by getActivity** [comment]
@jiasijiedajidali 小伙子，这个问题我没有办法解答你，因为我对你说的这个框架没有足够多的了解。
