### ISSUE TITLE
[疑惑]在本框架使用NestedScrollLinearLayout 与 使用NestedScrollView嵌套LinearLayout的区别是什么呢？

### ISSUE THREAD

**Issue by XXQAQ** [getActivity/NestedScrollLayout#4]
### 问题描述【必填】

见标题

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
@XXQAQ 小伙子，我现在才刚看到这个 issue，现在来解答一下你的疑惑。

**Comment by getActivity** [comment]
@XXQAQ 你可以将 Demo 工程中使用到 NestedScrollLinearLayout 类修改 LinearLayout 类，然后手指上下滑动对比一下，它们两个的效果是不一样的。

**Comment by getActivity** [comment]
@XXQAQ 另外你说的 NestedScrollView 嵌套 LinearLayout 区别是什么，我测试了一下，从效果上面没有太大的区别，但是有一点肯定是有区别，就是可以减少一层布局嵌套。

**Comment by Lewis-0710** [comment]
> @XXQAQ 另外你说的 NestedScrollView 嵌套 LinearLayout 区别是什么，我测试了一下，从效果上面没有太大的区别，但是有一点肯定是有区别，就是可以减少一层布局嵌套。

可是不支持設置圓角啊
