### ISSUE TITLE
[Bug]：使用了并不能使布局滚动，不知道是不是我使用错误

### ISSUE THREAD

**Issue by ZJFCany** [getActivity/NestedScrollLayout#6]
### 框架版本【必填】

2.0

### 问题描述【必填】

使用了并不能使布局滚动，不知道是不是我使用错误

### 复现步骤【必填】

![1721285611402](https://github.com/user-attachments/assets/20ee9985-9012-4512-a72a-b0ca6f584f6d)

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

红米

### 出现问题的安卓版本【必填】

11

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

任何机型都复现

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by ZJFCany** [comment]
![1721285611402](https://github.com/user-attachments/assets/112349bf-b8ec-466d-8e67-97d1d5a72169)

**Comment by getActivity** [comment]
NestedScrollLinearLayout 不是一个滚动控件，当然不支持滚动，你可以看一下代码注释，上面很清楚的写着，支持嵌套滚动的 LinearLayout，而不是写的是，支持滚动的 LinearLayout。

<img width="911" alt="image" src="https://github.com/user-attachments/assets/c408375f-8502-4f7f-820e-e8e2eae4a3ce">
